# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7cf953ef5b65fcd005056e9cda638af5b9ca2f2c32379b01d5e6e9342efee33f074ef79c64672e0608e3d07a71233f94ab1b9de32eb9169cd22db8b4ad9a148

test:
  secret_key_base: 21b3dd599248a5b1ba496cdefc35edf9fab3ec5af27df1466d8fee8019f10b5b371d179bb80b9d719f50682db0c3d2efdcdeaf851fef88db763c326a1bcbc646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
